# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d767019456d1e321d1512e4cd828e5185728cba3ba781c6d51a19a0899f8c7514e6cd6bae3e07a036281f9e56e65a634ec6d82bb35863d8eb9b678b4b4e56f6

test:
  secret_key_base: c21a31ae8b31f9b61cc0cd3c7f804353f671bdc083f7028d2a0e3b3423adfd232fd25d47b6588994599dd7c61328c494ea5f7813bd06d6fc97613f4bce6b5573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
